[INFO][2021-06-28 20:26:31,290] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:26:31,564] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:26:31,590] start_polling:360: Start polling.
[INFO][2021-06-28 20:26:47,954] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:26:48,000] start_polling:329: Goodbye!
[INFO][2021-06-28 20:29:22,411] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:29:23,634] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:29:23,635] start_polling:360: Start polling.
[ERROR][2021-06-28 20:29:27,598] start_polling:323: Task exception was never retrieved
future: <Task finished name='Task-14' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py:409> exception=AttributeError("'Functions' object has no attribute 'mamailing_subscribe_users'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "./main.py", line 65, in subscribe
    await func.mamailing_subscribe_users()
AttributeError: 'Functions' object has no attribute 'mamailing_subscribe_users'
[INFO][2021-06-28 20:29:31,974] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:29:31,974] start_polling:329: Goodbye!
[INFO][2021-06-28 20:29:46,981] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:29:47,210] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:29:47,211] start_polling:360: Start polling.
[ERROR][2021-06-28 20:29:47,608] start_polling:323: Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py:409> exception=AttributeError("'Functions' object has no attribute 'mamailing_subscribe_users'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "./main.py", line 65, in subscribe
    await func.mamailing_subscribe_users()
AttributeError: 'Functions' object has no attribute 'mamailing_subscribe_users'
[INFO][2021-06-28 20:30:07,434] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:30:07,435] start_polling:329: Goodbye!
[INFO][2021-06-28 20:30:15,976] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:30:16,297] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:30:16,298] start_polling:360: Start polling.
[ERROR][2021-06-28 20:30:16,767] start_polling:323: Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py:409> exception=AttributeError("'Functions' object has no attribute 'mamailing_subscribe_users'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "./main.py", line 65, in subscribe
    await func.mamailing_subscribe_users()
AttributeError: 'Functions' object has no attribute 'mamailing_subscribe_users'
[INFO][2021-06-28 20:30:19,801] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:30:19,801] start_polling:329: Goodbye!
[INFO][2021-06-28 20:30:48,464] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:30:48,694] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:30:48,695] start_polling:360: Start polling.
[ERROR][2021-06-28 20:30:50,730] mailing_subscribe_users:614: [mailing_subscribe_users] name 'message' is not defined
[INFO][2021-06-28 20:30:56,744] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:30:56,745] start_polling:329: Goodbye!
[INFO][2021-06-28 20:32:29,252] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:32:29,999] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:32:30,000] start_polling:360: Start polling.
[ERROR][2021-06-28 20:32:30,539] start_polling:323: Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py:409> exception=TypeError('mailing_subscribe_users() takes 1 positional argument but 2 were given')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "./main.py", line 65, in subscribe
    await func.mailing_subscribe_users(message)
TypeError: mailing_subscribe_users() takes 1 positional argument but 2 were given
[INFO][2021-06-28 20:32:35,633] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:32:35,634] start_polling:329: Goodbye!
[INFO][2021-06-28 20:32:38,459] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:32:38,700] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:32:38,701] start_polling:360: Start polling.
[ERROR][2021-06-28 20:32:39,092] start_polling:323: Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py:409> exception=TypeError('mailing_subscribe_users() takes 1 positional argument but 2 were given')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "./main.py", line 65, in subscribe
    await func.mailing_subscribe_users(message)
TypeError: mailing_subscribe_users() takes 1 positional argument but 2 were given
[INFO][2021-06-28 20:32:42,730] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:32:42,731] start_polling:329: Goodbye!
[INFO][2021-06-28 20:33:03,235] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:33:03,466] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:33:03,467] start_polling:360: Start polling.
[ERROR][2021-06-28 20:33:10,747] message_mailig:599: [Vanya None 1100858556] [message_mailig] Chat not found
[ERROR][2021-06-28 20:34:21,277] start_polling:328: Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py:409> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 467, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/utils/executor.py", line 323, in start_polling
    loop.run_forever()
  File "uvloop/loop.pyx", line 1370, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 550, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 467, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "./main.py", line 65, in subscribe
    await func.mailing_subscribe_users(message)
  File "/media/q/File/p/python/telegram/bot-aiogram/functions.py", line 605, in mailing_subscribe_users
    if str(time.strftime("%H:%M:%S")) == str("20:34:25"):
KeyboardInterrupt
[INFO][2021-06-28 20:34:21,286] stop_polling:435: Stop polling...
[INFO][2021-06-28 20:34:24,025] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:34:24,291] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:34:24,292] start_polling:360: Start polling.
[ERROR][2021-06-28 20:34:25,775] mailing_subscribe_users:614: [mailing_subscribe_users] Chat not found
[INFO][2021-06-28 20:43:37,871] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:43:38,106] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:43:38,106] start_polling:360: Start polling.
[ERROR][2021-06-28 20:44:00,607] mailing_subscribe_users:616: [mailing_subscribe_users] name 'message' is not defined
[INFO][2021-06-28 20:46:06,679] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:46:06,680] start_polling:329: Goodbye!
[INFO][2021-06-28 20:46:18,152] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:46:18,405] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:46:18,406] start_polling:360: Start polling.
[ERROR][2021-06-28 20:46:18,885] start_polling:323: Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py:409> exception=NameError("name 'asyncio' is not defined")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "./main.py", line 65, in subscribe
    asyncio.create_task(func.mailing_subscribe_users(message))
NameError: name 'asyncio' is not defined
[INFO][2021-06-28 20:46:50,492] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:46:50,493] start_polling:329: Goodbye!
[INFO][2021-06-28 20:47:00,598] _welcome:362: Bot: Database [@your_personal_database_bot]
[WARNING][2021-06-28 20:47:00,839] _skip_updates:358: Updates were skipped successfully.
[INFO][2021-06-28 20:47:00,840] start_polling:360: Start polling.
[ERROR][2021-06-28 20:47:10,569] mailing_subscribe_users:616: [mailing_subscribe_users] name 'message' is not defined
[INFO][2021-06-28 20:49:17,573] stop_polling:435: Stop polling...
[WARNING][2021-06-28 20:49:17,573] start_polling:329: Goodbye!
